[tool.poetry]
name = "python_api"
version = "0.1.0"
description = ""
authors = ["cosmo"]

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.2"
psycopg2-binary = "^2.9.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
