[tool.poetry]
name = "python_api"
version = "0.1.0"
description = ""
authors = ["cosmo"]

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.2"
pg8000 = "^1.31.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
