version: "3"

vars:
  IMAGE_REPO: cosmovagabond/k8s-test-python
  IMAGE_TAG: devops_test

tasks:
  build-container-image:
    desc: Build container image
    cmds:
      - docker build -t {{.IMAGE_REPO}}:{{.IMAGE_TAG}} --push .

  build-container-image-multi-arch:
    desc: Build multi-arch container image
    cmds:
      - |
        docker buildx build \
        --platform linux/amd64,linux/arm64 \
        -t {{.IMAGE_REPO}}:{{.IMAGE_TAG}} \
        --push \
        .

  install:
    desc: Install load generator dependencies
    cmds:
      - poetry install --no-root

  run_load:
    desc: Start load generator
    cmds:
      # api-golang is listening on port 8000
      - API_URL=http://localhost:8000/ DELAY_MS=100 poetry run python load_generator.py

  run_python_api:
    desc: Start python api
    cmds:
      # api-golang is listening on port 8000
      - API_URL=http://localhost:8000/ DELAY_MS=100 poetry run python main.py
