version: "3"

vars:
  DATABASE_URL: "postgres://postgres:youshallnotpass@localhost:5432/postgres"
  IMAGE_REPO: cosmovagabond/k8s-test-golang
  IMAGE_TAG: devops_test

tasks:
  install:
    desc: "download dependencies"
    cmds:
      - go mod tidy

  run:
    desc: "download dependencies"
    cmds:
      - echo $PWD
      - ls
      - DATABASE_URL={{.DATABASE_URL}} go run main.go

  build-container-image-ko:
    desc: Build container image
    cmds:
      - |
        KO_DOCKER_REPO='{{.IMAGE_REPO}}' \
          ko build \
          --bare \
          --tags={{.IMAGE_TAG}} \
          --platform=all

  build-container-image:
    desc: Build container image
    cmds:
      - docker build -t {{.IMAGE_REPO}}:{{.IMAGE_TAG}} --push .

  build-container-image-multi-arch:
    desc: Build multi-arch container image
    cmds:
      - task: build-container-image
