services:
  # PostgreSQL Database Service
  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      # This volume persists the database data
      - postgres-data:/var/lib/postgresql/data
      # This runs the init script on first startup
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  # Go API Service
  backend-go:
    build: ./backend-go
    container_name: go_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      # The connection string uses the service name 'db' as the host
      DATABASE_URL: "postgres://myuser:mypassword@db:5432/mydb?sslmode=disable"
    depends_on:
      - db

  # Python API Service
  backend-python:
    build: ./backend-python
    container_name: python_api
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgres://myuser:mypassword@db:5432/mydb"
    depends_on:
      - db
      
  # React Frontend Service
  frontend-react:
    build: ./frontend-react
    container_name: react_frontend
    restart: always
    ports:
      - "3000:80" # Map host port 3000 to Nginx container port 80
    depends_on:
      - backend-go
      - backend-python

volumes:
  postgres-data: {}