# ⛔️ DONT PUT SECRET FILES IN VCS
apiVersion: v1
kind: Secret
metadata:
  name: db-password
  namespace: welcome-webapp
type: Opaque
stringData:
  DATABASE_URL: postgres://postgres:youshallnotpass@postgres-postgresql.postgres.svc.cluster.local:5432/postgres
