name: Test Project

on:
    pull_request:
        branches:
            - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
        # Use a Node.js 20 Docker image
        image: node:20
    steps:
        - uses: actions/checkout@v3
          with:
            node-version: '20'
        # Install dependencies and run tests
        - run: npm ci
        - run: npm test
        - run: npm run build